statamic/eloquent-driver

src/Entries/EntryModel.php

This allows one to get data from within the JSON blob as if it was a native model. i.e. `$entry->foo` grabs `$data['foo']`.

get attributes from within the json blob

---

src/Commands/ImportEntries.php
src/Entries/EntryModel.php
src/Entries/EntryQueryBuilder.php

Fix multisite selector

---

src/Commands/ImportEntries.php

This PR fixes issue #75 by importing entries with no origin before importing items that do have an origin.
Fixes: #75

Modify entries import to defer import of entries with origin

---

composer.json
src/Collections/Collection.php

Once https://github.com/statamic/cms/pull/6983 is merged and released this will need added to eloquent.
Before merge we should also update the minimum Statamic core version in composer.json

Add originBehavior to collection

---

src/Taxonomies/TermQueryBuilder.php

When specifying `max_items: 1` for a term relation, the value is stored as a string instead of an array. This results in a fatal error trying to loop over a string.

Fixed fatal error when `max_items: 1` is used with terms

---

src/Taxonomies/Term.php

This will ensure localizations are stored correctly (fixes https://github.com/statamic/eloquent-driver/issues/78)

Fixed terms localization not working

---

database/migrations/create_asset_containers_table.php.stub
database/migrations/create_asset_table.php.stub
database/migrations/create_blueprints_table.php.stub
database/migrations/create_collections_table.php.stub
database/migrations/create_entries_table.php.stub
database/migrations/create_entries_table_with_string_ids.php.stub
database/migrations/create_fieldsets_table.php.stub
database/migrations/create_form_submissions_table.php.stub
database/migrations/create_forms_table.php.stub
database/migrations/create_globals_table.php.stub
database/migrations/create_navigation_trees_table.php.stub
database/migrations/create_navigations_table.php.stub
database/migrations/create_revisions_table.php.stub
database/migrations/create_taxonomies_table.php.stub
database/migrations/create_terms_table.php.stub

To improve perfomance for Postgres databases, the `json` columns can use the `jsonb` data type.
This is will reduce responsetimes drastically when dealing with large datasets.

Use `jsonb` data type for PostgreSQL to increase perfomance

---

tests/TestCase.php

The test suite currently outputs a whole bunch of `This test did not perform any assertions` messages. This is because of a change in a later version of Mockery.
See https://github.com/statamic/cms/pull/6689 for a more detailed explanation. This PR is just applying the same fix.

Add expectation to mocked version to fix assertion counts

---

src/Entries/EntryQueryBuilder.php
tests/Data/Entries/EntryQueryBuilderTest.php

Fix table name usage in clauses

---

src/Fields/BlueprintRepository.php

Fixes: #92, #93
Reference PR in core: https://github.com/statamic/cms/pull/6588

Update Blueprint repository to match method definitions with core

---

README.md

The readme mentions an incorrect file path to the trees file. This update fixes that.

Fix path to trees file in README

---

src/Assets/AssetRepository.php

Deleting an asset will fail if it doesn't have a metadata entry - `Call to a member function delete() on null`

Fixed asset calling delete on null

---

src/Collections/Collection.php

@robdekort found a lovely bug that when you have a dated collection and make it order able it wasn't honouring the order you set. So this fix changes it by not saving the `sortField` to the database when the collection is orderable.

Only save custom sort field and direction

---

src/Listeners/UpdateStructuredEntryOrder.php
src/ServiceProvider.php

Fixes #139
This adds an event listener that does the exact same thing as the core's UpdateStructuredEntryOrder listener.
It'll update the `order` column of entries when you save a tree.
It will only do it if entries are configured to be in Eloquent, and Collections are configured to not be.

Update entry order when saving a tree and collections are stored in files

---

src/Commands/ImportCollections.php
src/Commands/ImportForms.php
src/Fields/BlueprintRepository.php
src/Forms/FormModel.php
src/Forms/FormRepository.php
src/Forms/SubmissionModel.php
src/Structures/NavigationRepository.php

There are some references to models which are not called via app('...') but directly. That means that overriding those references is not possible. This PR fixes that.

Fixing some model references to configurable references

---

config/eloquent-driver.php
src/Collections/CollectionRepository.php
src/Jobs/UpdateCollectionEntryOrder.php

When updating the Entry Collection order with a large number of entries and an external search provider the performance can cause timeouts and page load failures.
Lets resolve this by making the update take place inside a job.
Fixes: #105

Change entry collection order update be a job

---

src/Forms/Submission.php

See:
https://github.com/statamic/cms/blob/3.4/src/Forms/Submission.php#L10
https://github.com/statamic/cms/blob/3.4/src/Forms/Submission.php#L152
https://github.com/statamic/cms/blob/3.4/src/Forms/Submission.php#L164
Currently we're missing events that are fired by default statamic and not by this module. 
Making code depending on these events unpredictable and most-likely non-functional.
This PR will bring those events inline with how they work in default Statamic.

Bring submission events inline with Statamic

---

src/Taxonomies/TermQueryBuilder.php

Having multiple terms with the same slug, in different taxonomies attached to the same collection, wrong terms will "bleed" into the list when querying `whereIn('id', [...])` through the OrderedQueryBuilder, as the taxonomy will not be filtered later on.

Fixed taxonomy not being respected when querying specific ids

---

src/Entries/Entry.php

To eliminate duplicate queries as noted here:
https://github.com/statamic/eloquent-driver/issues/110#issuecomment-1419022238

Use Entry facade for origins to avoid duplicate queries

---

src/Commands/ImportEntries.php
src/Entries/Entry.php

Importing entries has been broken, not totally sure when we lost sync with core, but something has changed that stopped us getting a Eloquent entry class and instead a Stache entry class.
Luckily we have an approach that worked with the other repositories, so let's move entries to using that same approach.

Entry import: follow makeModelFromContract() approach used in other imports

---

src/Entries/Entry.php

When calling `$entry->origin(null)`, also set the `origin_id` on the model.
Otherwise, subsequent calls to `$entry->origin()` will fall back to reading the origin_id on the model, leaving you no way to truly null it out.
This is necessary when you delete an entry and choose to "detach" the localizations. All of the descendant entries should get the origin removed. Before this PR, when you tried to do that, the origin just sticks around. You end up with an error when trying to delete an entry instead of it actually getting deleted.
By solving this, the removal of the origin_id foreign key constraint onDelete cascade in #100 shouldn't be an issue.

Set origin id on entry model

---

src/Entries/Entry.php
src/Entries/EntryRepository.php
tests/Entries/EntryTest.php

As discussed [here](https://github.com/statamic/eloquent-driver/issues/112), we should store origin entry data alongside localisation data so it can be queried at the database level.
Let me know if youre happy with this approach as I'll need to add some test coverage on this before it should be merged.

Store origin data alongside localized data

---

src/Fields/BlueprintRepository.php
tests/Data/Fields/BlueprintTest.php

When toggling the blueprint visibility in the CP hidden it was getting stuck on 'hidden', and could not be reverted from that state. This is due to how the `contents` are being merged in and out of the database.
This change does a hard check on hidden before saving the model and removes it from the data being stored when not required. 
I also took the opportunity to begin test coverage for blueprints.
Fixes: https://github.com/statamic/eloquent-driver/issues/159

Allow 'hidden' blueprints to be un-hidden

---

src/Entries/EntryQueryBuilder.php
tests/Data/Entries/EntryQueryBuilderTest.php

This PR checks for the presence of offset without limit on entry queries, which throws an error on some database engines (looking at you MySQL). 
Laravel have chosen to not provide a work around in their query builder, but we should as the Stache allows this and we want to be compatible.
Closes #175

Fix offset being specified without limit and without pagination on EntryQueryBuilder

---

database/migrations/create_global_variables_table.php.stub
database/migrations/create_globals_table.php.stub
database/migrations/updates/update_globals_table.php.stub
src/Commands/ImportGlobals.php
src/Globals/GlobalRepository.php
src/Globals/GlobalSet.php
src/Globals/GlobalSetModel.php
src/Globals/Variables.php
src/Globals/VariablesModel.php
src/ServiceProvider.php
src/Updates/SplitGlobalsFromVariables.php
tests/TestCase.php

Following on from the conversation in https://github.com/statamic/eloquent-driver/issues/128, it makes sense to split globals and variables into separate tables, enabling splitting of configuration from data.
Ideally we would be able to offer a config for letting you opt into eloquent globals and variables separately, but from what I can see this is not possible in core as things stand. Scope for future development.
Closes: https://github.com/statamic/eloquent-driver/issues/128

Restructure global variables to use its own table

---

src/Entries/Entry.php
tests/Entries/EntryTest.php

Add computed values to the data being stored to `entries`, so its available to the query builder.
Fixes: https://github.com/statamic/eloquent-driver/issues/149

Ensure computed values are stored in the database so they can be queried

---

config/eloquent-driver.php
src/Assets/AssetRepository.php
src/ServiceProvider.php

This PR adds a config option and app binding for the asset class, allowing a different class to be used while using the same asset repository.
Fixes #131

Add config for asset class to make it easier to to customize

---

src/Entries/EntryQueryBuilder.php
tests/Data/Entries/EntryQueryBuilderTest.php

fixes https://github.com/statamic/eloquent-driver/issues/153

Ensure it is possible to order entries by integer, float or date fields

---

composer.json
src/Collections/Collection.php

Closes #161
This bumps the minimum version of Statamic to where the methods are available, so we don't need the overrides anymore.
This requires 4.6.0 to be tagged.

Remove custom collection methods

---

config/eloquent-driver.php
src/Commands/ImportAssets.php
src/Commands/ImportCollections.php
src/Commands/ImportNavs.php
src/ServiceProvider.php
src/Structures/NavTreeRepository.php

Fixes https://github.com/statamic/eloquent-driver/issues/147
This small pull request enables the possibility to define a different driver for collections and collection trees.
This can be useful if you want your collection definitions to be stored as flat files (so they're available and synced throughout all environments), but have eloquent entries which has a direct impact on the tree structure (which would not be the same in all environments).
All tests are passing, but I saw no config-based tests I could alter or enrich. However, it was tested in all 5 possible configurations on a local site:
- driver -> eloquent
tree_driver -> commented
- driver -> file
tree_driver -> commented
- driver -> eloquent
tree_driver -> eloquent
- driver -> eloquent
tree_driver -> file
- driver -> file …

Split configs for asset containers, collection trees and navigation trees

---

src/Assets/AssetContainer.php
src/Collections/Collection.php
src/Entries/Entry.php
src/Forms/Form.php
src/Forms/Submission.php
src/Revisions/Revision.php
src/Structures/CollectionTree.php
src/Structures/Nav.php
src/Structures/NavTree.php
src/Taxonomies/Taxonomy.php
src/Taxonomies/Term.php

Seeing as we let models be bound in the config file, the fromModel methods should not force a certain model class. Otherwise this means developers are forced to extend our models, which they may have good reasons not to.

`fromModel` should accept any Eloquent model rather than forcing a specific model

---

src/ServiceProvider.php

_php artisan vendor:publish --provider="Statamic\Eloquent\ServiceProvider" --tag=migrations_ was returning _ERROR  Can't locate path: <vendor/statamic/eloquent-driver/src/../database/migrations/create_global_varaibles_table.php.stub>_  before the typo fix

fixed typo in global variables migration file name

---

src/Commands/ExportBlueprints.php

I tried to export my blueprints and fieldsets back to the file system but there was an error. So my blueprint were exported but not the fieldsets.
```
Statamic\Fields\FieldsetRepository::find(): Argument #1 ($handle) must be of type string, null given
```
This change fixed the issue and allowed me to export everything properly.
Sets to reproduce:
- php please eloquent:import-blueprints
- php please eloquent:export-blueprints

Fix fieldsets export

---

src/ServiceProvider.php

This PR adds a "Statamic Eloquent Driver" block to `php please support:details` showing the repository configuration, so it does not need to be requested when supporting issues.
Example of how it looks:

Add a block to `php please support:details` to show repository config

---

composer.json
src/Entries/EntryRepository.php
tests/Entries/EntryTest.php

In statamic/cms#8505 descendants will be saved. There is no longer a need to do it from the Eloquent repository side. It would only cause them to be saved twice.
I'm bumping the requirement of cms to the version where that PR would be available.
This is not currently an issue, but will be once that PR is released. It's only minor - the entries would be double saved, and EntrySaved events dispatched multiple times. Database `update` queries wouldn't even run since the model would have no changes the second time.

Don't double-save descendants

---

src/ServiceProvider.php

The eloquent global repository was only being registered if the variables one was, which is no longer necessarily the case. This PR fixes that.

Bug fix on global repository registration

---

composer.json
src/Structures/CollectionTreeRepository.php
src/Structures/NavTreeRepository.php

This PR binds our collection and nav trees so when new instances are created by any repository (stache or eloquent) we get the instance we expect.
Requires: https://github.com/statamic/cms/pull/8658
Replaces: https://github.com/statamic/eloquent-driver/pull/199

Add bindings for eloquent collection and nav trees

---

src/Entries/EntryRepository.php
src/Taxonomies/TermRepository.php

Hi everyone,
This fix will prevent `Blink::once()` from unexpectedly returning an array when the URI contains certain special characters. I encountered this issue because on one of our sites, visitors have tried navigating to the following URL:  `https://example.com/blog/skale-v-2-(select(0)from(select(sleep(15)))v)%2f*'+(select(0)from(select(sleep(15)))v)+'%22+(select(0)from(select(sleep(15)))v)+%22*%2f`. This in turn triggered the following error: `Error: Call to a member function id() on array`.
Currently, a URI like above makes `Blink::once()` return the following:
```
array:1 [ // vendor/statamic/eloquent-driver/src/Entries/EntryRepository.php:45
"eloquent-entry-/blog/skale-v-2-(select(0)from(select(sleep(15)))v)%2f*'+(select(0)from(select(sleep(15)))v)+'%22+(select(0)from(select(slee …
```

[Fix] Encode uri for use in blink key

---

config/eloquent-driver.php
src/Collections/CollectionRepository.php

Fixes #211 .
Had to add `onConnection` conditionally, as `onConnection('default')` is not a thing.

Ability to config queue connection for UpdateCollectionEntryOrder job

---

src/Revisions/Revision.php

If https://github.com/statamic/cms/pull/8551 merges, this PR will add the same functionality to eloquent revisions.

Add `RevisionSaving` event

---

README.md
database/migrations/create_asset_table.php.stub
database/migrations/updates/update_assets_table.php.stub
src/Assets/Asset.php
src/Assets/AssetContainer.php
src/Assets/AssetContainerContents.php
src/Assets/AssetModel.php
src/Assets/AssetQueryBuilder.php
src/Assets/AssetRepository.php
src/Commands/SyncAssets.php
src/ServiceProvider.php
src/Updates/AddMetaAndIndexesToAssetsTable.php
tests/Data/Assets/AssetQueryBuilderTest.php
tests/Data/Entries/EntryQueryBuilderTest.php

This PR brings an AssetQueryBuilder to eloquent driver, reducing the number of file systems calls made and removing the need for a stache cache of the path listing.
This is particularly useful for sites with a large number of assets in cloud storage, as asides from initially populating a folder cache and accessing assets individually, all queries, filtering and meta will be only accessed from the database.
Replaces https://github.com/statamic/eloquent-driver/pull/207
Closes https://github.com/statamic/eloquent-driver/issues/191

Make AssetQueryBuilder for performance gains

---

src/Assets/Asset.php
src/Assets/AssetContainerContents.php
src/Commands/SyncAssets.php

This PR fixes an issue with the sync command and directory listing using the asset query builder. It also adds metaExists caching to the asset class to prevent multiple duplicate queries.
Closes https://github.com/statamic/eloquent-driver/issues/222
Closes https://github.com/statamic/eloquent-driver/issues/223

Fix issues with directory listing not returning all folders

---

database/migrations/updates/add_id_to_attributes_in_revisions_table.php.stub

See https://github.com/statamic/eloquent-driver/pull/231#issuecomment-1896319900

Use `chunkById` to prevent unexpected database behaviour

---

src/Assets/Asset.php

It may be, that I had corrupt assets in my import.
To not abort the import script, I added a check, if the extension could be found.
In case it returns null, the import aborts.
```
Integrity constraint violation: 1048 Column 'extension' cannot be null
```
To improve the check, some kind of notice, that a certain image could not be imported may be nice.
Anyways, I thought I'll drop this little change to see, if this is something that should be implemented.

Check if a asset extension could be found

---

composer.json

Hi! We check the licences of our packages in our CI and get a warning¹ because no licence is detected. 😅 
Note that this change would also require a release to reach [Packagist](https://packagist.org/packages/statamic/eloquent-driver).
---
¹ `There is no license information available for the latest version (v3.0.5) of this package.`

add license to `composer.json`

---

composer.json
src/Assets/Asset.php
src/Entries/Entry.php
src/Taxonomies/Term.php
tests/Data/Entries/EntryQueryBuilderTest.php
tests/Entries/EntryTest.php

This goes along with statamic/cms#5502 to allow `isDirty` etc to work correctly when using the Eloquent driver.

Apply syncOriginal for dirty state tracking

---

README.md
src/ServiceProvider.php
src/Updates/AddBlueprintToEntriesTable.php
src/Updates/AddMetaAndIndexesToAssetsTable.php
src/Updates/SplitGlobalsFromVariables.php

I'm building a new `php please install:eloquent-driver` command into Statamic Core, which will make the process of moving "things" to the Eloquent Driver much easier.
The command will install the package & let you configure which repositories you want to move over. 
As part of these changes, I didn't want to force users to publish *all* of the Eloquent Driver's migrations, even if they're only planning on switching one of two of the repositories.
This PR makes that possible by splitting the migrations into separate publish tags, grouped by repository.

Allow publishing migrations separately

---

src/ServiceProvider.php

This pull request attempts to fix an issue identified in [the comments of my previous PR](https://github.com/statamic/eloquent-driver/pull/253#issuecomment-1985330614), where the Eloquent Driver's migrations were being loaded, even though they had already been published and the tables already existed.
Since the filenames of migrations changed in #253, Laravel thought the migrations it was loading directly from the package's `database/migrations` directory were new migrations so it attempted to run them causing an error.
To make it easier to understand, here's what lead to the error happening:
1. Using the Eloquent Driver v3.2 or below, publish its migrations w/ `php artisan vendor:publish`
* The migrations will have been published into `database/migrations`.
* The filenames for each of …

Migrations are publishable, they don't need to be loaded

---

src/Assets/Asset.php

As [reported here](https://github.com/statamic/eloquent-driver/issues/251) uploading an asset where the name changes causes a duplicate database entry.
This PR checks the dirty state of the asset to work out if there is a model to update.
Closes https://github.com/statamic/eloquent-driver/issues/251

Fix asset uploading bug

---

config/eloquent-driver.php
tests/TestCase.php

Right now, when you install the Eloquent Driver, *everything* will become driven by Eloquent. However, in a lot of cases, you might only want to move one driver (eg. `assets`) to the database and keep the rest in flat-files. 
This PR changes the default `driver` of all the repositories and adds to the `TestCase` to ensure the repository is switched to `eloquent` when running the test suite.
This PR pairs with statamic/cms#9669, which will let you enable "parts" of the Eloquent Driver as needed.

Make drivers opt-in, rather than opt-out

---

tests/Data/Entries/EntryQueryBuilderTest.php

This pull request fixes two failing tests in the `EntryQueryBuilderTest`.
* `entry_is_found_within_all_created_entries_using_entry_facade_with_find_method` was failing due to the timestamps in the searched & retrieved entries not matching. Freezing time using Laravel's `$this->freezeTime()` helper fixed this.
* `entry_is_found_within_all_created_entries_and_select_query_columns_are_set_using_entry_facade_with_find_method_with_columns_param` was failing due to the retrieved entry only returning `foo` and `collection`, where the comparison was expecting the entire entry array. 
These fixes were "cherry picked" out of changes in #273.

Fix failing tests in `EntryQueryBuilderTest`

---

src/Assets/Asset.php

The blink meta cache currently persists after save, delete etc, which can cause issues with bulk importing assets or accessing them programatically.
This PR ensures the blink cache is cleared on save, re upload etc.

Clear blink cache on asset save

---

composer.json
src/Entries/EntryQueryBuilder.php
tests/Data/Entries/EntryQueryBuilderTest.php
tests/Factories/EntryFactory.php

This pull request fixes an issue I ran into this morning when using the REST API alongside the Eloquent Driver.
Essentially, when the REST API queries to get entries, it filters for entries where `status` `is` `published`. However, when using the Eloquent Driver, no entries were being returned. 
I've fixed this issue by copying over the recent changes around entry statuses to the Eloquent Driver (related: #9317). 
The implementation is *mostly* the same as it is in Core. However, the main difference is the fact the Eloquent Driver's query builder doesn't maintain a `$collections` property to track the queried collection, instead we're just using `$this->wheres()`

Fix querying statuses

---

src/Updates/SplitGlobalsFromVariables.php

This PR fixes the path to the global variables update which was missed as part of https://github.com/statamic/eloquent-driver/pull/253/files
Closes https://github.com/statamic/eloquent-driver/issues/280

Fix migration path for global variables update

---

database/migrations/updates/relate_form_submissions_by_handle.php.stub

As reported on discord there is an error in the form migration, we needed to drop the foreign key first.
This PR ensures that is done.

Drop foreign key on form_id

---

src/ServiceProvider.php

This pull request adds the recently introduced "Tokens" repository to the list of outputted drivers in the `php artisan about` / `php please support:details` commands.
The "Tokens" repository was added in #277.

Add "Tokens" driver to `artisan about` command output

---

composer.json
database/migrations/2024_05_15_100000_modify_form_submissions_id.php
src/Commands/ImportForms.php
src/Forms/Submission.php
src/Forms/SubmissionModel.php
src/ServiceProvider.php
src/Updates/ChangeFormSubmissionsIdType.php
tests/Forms/FormSubmissionTest.php

This PR updates the id type on form_submissions to be a float, rather than an int, so that out of the box it works on Postgres.
@andreas-eisenmann would you mind checking that this migration works in your situation?
Closes https://github.com/statamic/eloquent-driver/issues/286

Change ID type on form_submissions to be a float

---

src/Assets/Asset.php
src/Assets/AssetContainer.php
src/Commands/ImportAssets.php

When working on https://github.com/statamic/eloquent-driver/pull/296 I noticed there was a duplication of code in AssetContainer which we should avoid. 
I also took the chance to update the makeModelFromContract methods in assets and containers to not save the model, as it should only make the instance, after which you can decide if you want to save it or not.

Refactor makeModelFromContract on assets and containers

---

src/Collections/CollectionRepository.php

This PR optimises the collection query in the `updateEntryOrder` method by making use of `ids` which are redundant in the current method.
On some of our sites this caused a large number of jobs to be dispatched to the queue when entries were reordered in collection trees. This fix has resolved our issue when applied via composer patch.
The fix is akin to logic already in use in the `updateEntryUris` method

make use of $ids in updateEntryOrder method

---

config/eloquent-driver.php
src/Fields/BlueprintRepository.php
src/ServiceProvider.php
tests/Data/Fields/BlueprintTest.php

This PR adds a config to choose which blueprint namespaces are eloquent driven and which are not. For example, you may want form blueprints in the database but others to be file based.
Closes https://github.com/statamic/eloquent-driver/issues/204

Support mixed repository blueprints

---

src/Collections/CollectionRepository.php

As reported here: https://github.com/statamic/eloquent-driver/pull/301#issuecomment-2175683899

Fix bug in updateEntryUris and updateEntryOrder

---

.gitignore
config/eloquent-driver.php
src/Commands/ImportBlueprints.php
src/Fields/BlueprintRepository.php
src/Fields/FieldsetRepository.php
src/ServiceProvider.php
tests/Commands/ImportBlueprintsTest.php

This PR allows blueprints and field sets to be run in split repository mode, ie the blueprints could be eloquent driven and field sets file driven, or vice versa.
It also fixes some of the code introduced in https://github.com/statamic/eloquent-driver/pull/300 to handle methods that were missed initially.

Allow blueprints and field sets to be split repository

---

database/migrations/2024_05_15_100000_modify_form_submissions_id.php

Change the form id migration to use double as float isn't consistent in MySQL

Use double instead of float for MySQL compatability

---

tests/Commands/ImportAssetsTest.php
tests/Commands/ImportBlueprintsTest.php
tests/Commands/ImportCollectionsTest.php
tests/Commands/ImportEntriesTest.php
tests/Commands/ImportFormsTest.php
tests/Commands/ImportGlobalsTest.php
tests/Commands/ImportNavsTest.php
tests/Commands/ImportRevisionsTest.php
tests/Commands/ImportTaxonomiesTest.php
tests/Data/Assets/AssetQueryBuilderTest.php
tests/Data/Entries/EntryQueryBuilderTest.php
tests/Data/Fields/BlueprintTest.php
tests/Data/Globals/GlobalSetTest.php
tests/Data/Globals/VariablesTest.php
tests/Data/Taxonomies/TermQueryBuilderTest.php
tests/Entries/EntryModelTest.php
tests/Entries/EntryTest.php
tests/Forms/FormSubmissionTest.php
tests/Repositories/AssetContainerRepositoryTest.php
tests/Repositories/CollectionRepositoryTest.php
tests/Repositories/GlobalRepositoryTest.php
tests/Repositories/NavigationRepositoryTest.php
tests/Repositories/TaxonomyRepositoryTest.php
tests/Repositories/TokenRepositoryTest.php

PHPUnit has started throwing deprecation warnings on the use of `/** @test **/` and dataproviders in comments. 
This PR updates the test suite to use attributes instead, which is going to be the only supported way from PHPUnit 12+.

Move to PHPUnit attributes

---

src/Forms/Submission.php
tests/Forms/FormSubmissionTest.php

As we no longer store the `date` in the model's data, we need to instead use the `created_at` value from the model for the submission date.

Use model `created_at` for form submission date()

---

src/Assets/AssetContainerContents.php
src/Commands/SyncAssets.php
tests/Assets/AssetContainerContentsTest.php

Now that we have an eloquent AssetContainerContents we should go the whole haul and use it to build the folder list as it will be significantly quicker than querying the file system directly.
This PR implements it, as well as the changes needed to the SyncAssets command to prevent it trying to use the AssetContainerContents directory list, as initially this will be empty.
Closes https://github.com/statamic/eloquent-driver/issues/294

Use database to build asset folder list

---

src/Commands/ImportBlueprints.php
tests/Commands/ImportBlueprintsTest.php

When importing add-on namespaced field sets and blueprints from the stache the namespace (for blueprints) is prefixed with vendor, and for field sets the handle is prefixed too. 
This PR updates the logic to handle those appropriately.

Handle vendor namespaces and handle for blueprints and fieldsets

---

src/Forms/SubmissionQueryBuilder.php

Submissions are not sortable due to this query which expects the date to be in the data.
This issue is a regression from https://github.com/statamic/eloquent-driver/pull/306 where the date field is grabbed from the created_at column instead. 
Result is that old submissions are sortable due to having a date property in data, but new entries do not.
Current query.
`select * from form_submissions where form = 'tip_os' order by json_unquote(json_extract(data, '$."date"')) desc limit 100 offset 0`
This PR changes the query builder to use the `created_at` column for sorting
The new query will look like this:
`select * from form_submissions where form = 'tip_os' order by created_at desc limit 100 offset 0`

use created_at column for submission sorting

---

src/Commands/ExportNavs.php
src/Structures/CollectionTree.php
src/Structures/Nav.php
src/Structures/NavTree.php

This PR prevents the stache specific `initial_path` from being added to eloquent models.

Remove `initial_path` from import and export data

---

composer.json
config/eloquent-driver.php
database/migrations/2024_07_16_100000_create_sites_table.php
src/Commands/ExportSites.php
src/Commands/ImportSites.php
src/ServiceProvider.php
src/Sites/SiteModel.php
src/Sites/Sites.php
tests/Commands/ImportSitesTest.php
tests/Sites/SitesTest.php
tests/TestCase.php

This PR adds the ability to store sites in Eloquent rather than YAML on the filesystem.
Tasks:
Closes https://github.com/statamic/eloquent-driver/issues/320

Store sites in eloquent

---

database/migrations/updates/relate_form_submissions_by_handle.php.stub

This PR updates the form_submissions update migration to check it needs to be run. It also ensures we only drop the foreign key if it exists.
Closes: https://github.com/statamic/eloquent-driver/issues/323
Fixes: https://github.com/statamic/eloquent-driver/pull/285#issuecomment-2230351766

Fix migration errors on form_submissions

---

composer.json
src/Structures/Nav.php

PR 9229 on statamic/cms will introduce canSelectAcrossSites() to Nav's, this PR enables support for storing it.
Related: https://github.com/statamic/cms/pull/9229

Support canSelectAcrossSites on navs

---

database/migrations/updates/relate_form_submissions_by_handle.php.stub
database/migrations/updates/update_assets_table.php.stub

SQLite requires deleting the indexes before deleting the column. Relates to this: https://github.com/laravel/framework/pull/51373

Drop indexes before dropping the column

---

src/Forms/Form.php
src/Forms/FormRepository.php
src/Forms/SubmissionQueryBuilder.php
tests/Forms/FormTest.php

Hello everyone!
We stumbled upon a bug on `/admin/forms`. We would get endless loading screens and eventually timeouts when visiting this page. We have quiet an amount of form submissions (~150.000), and the query builder in the current setup retrieves all submissions, with the form for every one of them.
We're using Statamic 5 with this package, and even though we were able to fix this in the `FormsController` of the `statamic/cms` package (see https://github.com/statamic/cms/pull/10534), we figured this could still cause problems for other scenarios outside of the `FormsController`. So we wanted to propose it.
The proposed changes retrieve all forms only once before being connected to each submission, instead of retrieving the form every time. This drastically decreases the amount of …

Only retrieve forms once instead of for every item

---

src/Structures/Nav.php

Hi!
This change fixes the following error we receive when navigating to the CP /navigation/<nav_name>:
```
Statamic\Support\Str::bool(): Argument #1 ($value) must be of type bool, null given, called in /<redacted>/storage/framework/views/f7f7a695478ceb1af2141e5f7389a1b0.php on line 21 (View: /<redacted>/vendor/statamic/cms/resources/views/navigation/show.blade.php)
```
This started happening after updating Composer dependencies, limited to patch and minor versions. The change in this PR is a possible fix, but that depends on if the default is considered `false`. Otherwise another option could be:
```diff
// vendor/statamic/cms/src/Structures/Nav.php
public function canSelectAcrossSites($canSelect = null)
{
return $this
->fluentlyGetOrSet('canSelectAcrossSites')
+        ->setter(function …
```

Fall back to boolean instead of null

---

src/Updates/RelateFormSubmissionsByHandle.php

This PR updates the update script to only run if we actually have the table

Only run RelateFormSubmissionsByHandle when we have form submissions

---

src/Fields/BlueprintRepository.php

This PR updates the logic of where the default blueprint namespace is stored to take into account whether eloquent is being used for all blueprints or not.

Empty namespace should default to file when namespaces is not `all`

---

composer.json
src/Forms/Form.php
tests/Forms/FormTest.php

This PR adds support for storing form data from extra config which was added to core in https://github.com/statamic/cms/pull/8491
Closes https://github.com/statamic/eloquent-driver/issues/341

Store form data

---

src/Taxonomies/TermQueryBuilder.php

This PR updates the collection checking clause in the TermQueryBuilder to be more performant.
Previously we were looping over all entries to get their terms, and when the number of entries increases this became an issue. Now, we loop over the terms and check if an entry has that term, and if so we query for it, otherwise we don't.
The hope is that most users will have less terms than entries. 
Ideally we'd have a pivot table of some sort but that would require significant changes in core.

Attempt to make term <> collection query more performant

---

src/Commands/ExportSites.php
tests/Commands/ExportSitesTest.php

This pull request fixes an issue with the `php please eloquent:export-sites` command, where it would export `lang` as an empty string and leave `attribues` as an empty array.
Before this PR:
```yaml
en:
name: 'The Getaway 1'
lang: ''
locale: en_US
url: /
attributes: {  }
de:
name: 'Die Flucht 2'
lang: ''
locale: de_DE
url: /de/
attributes: {  }
fr:
name: "L'Escapade 2"
lang: ''
locale: fr_FR
url: /fr/
attributes: {  }
```
After this PR:
```yaml
en:
name: 'The Getaway'
locale: en_US
url: /
de:
name: 'Die Flucht'
locale: de_DE
url: /de/
fr:
name: "L'Escapade"
locale: fr_FR
url: /fr/
```
This PR also adds an `ExportSitesTest` to cover the export sites command.

`export-sites` command: Prevent `lang` and `attributes` being exported with empty values

---

src/Commands/SyncAssets.php

The root folder of the container is listed as `/` in the database. Since the default was an empty string the default folder was never synced. For us this resulted in a big list of assets in assets meta that were no longer present on disk causing false 404's on pages.
This PR sets folder to `/` by default so the root folder (of the container) is also synced.

The root folder is / and not empty otherwise it's skipped

---

src/Assets/AssetContainerContents.php
tests/Assets/AssetContainerContentsTest.php

This PR updates the asset container contents folder filtering to ensure the folder finishes with /, which resolves any issues with folders starting with the same string.
Closes #355

Ensure asset container contents folder check finishes with /

---

src/Assets/AssetContainer.php
tests/Commands/ImportAssetsTest.php

fixes https://github.com/statamic/eloquent-driver/issues/359

Prevent freezing of ImportAssets for asset meta data when importing a large number of files

---

src/Commands/ExportEntries.php

This PR updates the export entries logic to use the model specified in the config, rather than forcing a numeric ID based model. This allows us to check if its a UUID model and if so also to export out IDs.
@lokmanm this is what I was meaning.
Closes https://github.com/statamic/eloquent-driver/issues/361

Fix entries export to use correct model, blueprint column, and set ID when exporting UUIDs

---

src/Globals/GlobalVariablesRepository.php

This PR ensures we use the variables model defined in the config.
Closes https://github.com/statamic/eloquent-driver/issues/369

Use variables model defined in config

---

src/Sites/Sites.php

This PR ensures an empty site `lang` is not inserted to the database by falling back to the language in the locale, or `en` if no locale is present
Closes https://github.com/statamic/eloquent-driver/issues/371

Fallback to locale or 'en' when site lang is not present

---

src/Taxonomies/TermQueryBuilder.php
tests/Data/Taxonomies/TermQueryBuilderTest.php

Working on a draft to fix issue #373 
The current implementation does not yet pass the tests due to not being fully db driver independent. 
The test fails because `JSON_QUOTE` seems to behave different in sqllite than mysql.
The `JSON_QUOTE` should probably not be hard coded here as well because we can't assume the db driver that is in use.
Closes https://github.com/statamic/eloquent-driver/issues/373

Optimize taxonomy <> collection queries

---

src/Assets/AssetContainer.php
src/Collections/Collection.php
src/Structures/Nav.php
src/Taxonomies/Taxonomy.php

This PR updates any config `settings` to merge with exiting values if present, ensuring that any extra (non-CP) config fields are not overwritten.
Closes https://github.com/statamic/eloquent-driver/issues/380

Allow non-CP collection config fields to persist

---

src/Taxonomies/Term.php
tests/Terms/TermTest.php

Make sure we're using the original slug to query for a term after an update.
Prevents duplicates being created when changing a term's slug in the control panel.
Probably needs tests to avoid regressions.
Fixes #383

Prevent creation of duplicate terms on slug change

---

src/Entries/Entry.php

This PR updates entry saving to use the routableUri, not the uri, which ensures we always have the latest uri in the database, even when the entry is new or when the slug is changed.
Closes https://github.com/statamic/eloquent-driver/issues/391

Ensure we store the latest Entry uri

---

src/Commands/ExportForms.php
src/Commands/ImportForms.php

This PR updates importing and exporting form submissions to be more aware of the form submission repository and contracts, clearing resolved instances where necessary.
Closes https://github.com/statamic/eloquent-driver/issues/388
Closes https://github.com/statamic/eloquent-driver/issues/389

Fix issues with importing and exporting forms

---

src/Commands/ExportTaxonomies.php

I needed to export taxonomies but didn't need terms, I then saw that the import command comes with arguments that allows you to import just taxonomies or terms.
This PR adds the same arguments to the export command.
```shell
php please eloquent:export-taxonomies --only-taxonomies
php please eloquent:export-taxonomies --only-terms
```

Adds Taxonomy export arguments, matching import

---

database/migrations/2024_03_07_100000_create_form_submissions_table.php

I ran into an issue while migrating form submissions from files to eloquent.
Some of the handles of my forms are longer than 30 characters, so i ran into an exception because there's currently a max length of 30 on the form column in the form submissions table.
In the forms table, this column has 255 characters. Not sure why the discrepancy is there (maybe because of the index on the column?)
I fixed my migration by adjusting the migration file for submissions like I did below.

Adjust length of form handle column in form submission table

---

src/Revisions/RevisionRepository.php

Statamic revisions are expected to be returned in chronological order. 
When using file based revisions, this is always the case, since the revisions are written in there in correct order and read back line-by-line.
When using eloquent and for example postgres, the ordering of the returned rows is undefined and depends on postgres internals, therefore an explicit `orderBy` clause is introduced.

return revisions in chronological order

---

README.md

This pull request updates the docs around "Using dedicated columns for data" to clarify that you might need an Eloquent cast for more than just `json`/`integer` columns, and to clarify that you should update the `model` key in the config file.

Update dedicated column docs

---

.github/workflows/tests.yml
composer.json

This pull request drops support for Laravel 10, and therefore also drops support for PHP 8.1.

[5.x] Drop Laravel 10 Support

---

README.md
src/Assets/AssetContainerModel.php
src/Assets/AssetModel.php
src/Collections/CollectionModel.php
src/Entries/EntryModel.php
src/Fields/BlueprintModel.php
src/Fields/FieldsetModel.php
src/Forms/FormModel.php
src/Forms/SubmissionModel.php
src/Globals/GlobalSetModel.php
src/Globals/VariablesModel.php
src/Revisions/RevisionModel.php
src/Sites/SiteModel.php
src/Structures/NavModel.php
src/Structures/TreeModel.php
src/Taxonomies/TaxonomyModel.php
src/Taxonomies/TermModel.php
src/Tokens/TokenModel.php

This pull request converts the `$casts` property on models to a method, now that Laravel 11 is the minimum version.

[5.x] Convert `$casts` property to method

---

src/Commands/SyncAssets.php

Closes https://github.com/statamic/eloquent-driver/issues/426

Ensure subfolder starts with / for comparison when syncing assets

---

src/Entries/EntryQueryBuilder.php

This ensures that `func_num_args()` in the parent `EloquentQueryBuilder` class returns the correct number of passed arguments to the `->where()` method.
This is necessary so the operator & value can be prepared appropriately (see statamic/cms#11805).
Partially fixes #424.

`EntryQueryBuilder::where()`: Forward all arguments to parent, instead of passing them manually

---

database/migrations/entries/2024_03_07_100000_create_entries_table.php
database/migrations/entries/2024_03_07_100000_create_entries_table_with_string_ids.php
database/migrations/updates/add_index_to_date_on_entries_table.php.stub
src/ServiceProvider.php
src/Updates/AddIndexToDateOnEntriesTable.php

This is a very simple PR to add an index to the `date` column of the `entries` table.
Sorting by the date column is a pretty common operation and it can be quite expensive without the index. In a low memory setup I would get a `QLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size` error even with just 60.000 entries, which is solved just by adding this index.
If there is another reason the date column is not indexed, sorry in advance!

Add index to the date column

---

src/Taxonomies/TermRepository.php
tests/Terms/TermTest.php

@ryanmitchell I think this was the other culprit for all the slowness.
The `TermRepository` was calling `$this->ensureAssociations();` which populates the `associations` index : 
```
protected function ensureAssociations()
{
Taxonomy::all()->each(function ($taxonomy) {
$this->store->store($taxonomy->handle())->index('associations');
});
}
```
This store is quite complex (over 10MB in my case) and it's probably not required when using the eloquent driver.
I also added a test to make sure the Terms facade still gets the correct count.
PS. With this change and your other PR the first page load is under 1 second.

Remove ensure associations

---

src/Entries/EntryQueryBuilder.php
src/Entries/EntryRepository.php
tests/Entries/EntryTest.php
tests/Terms/TermTest.php

When getting the where's for taxonomy lookups we should do another entry query, rather than relying on stache associations. This is a big performance win when you have lots of terms.

Taxonomy wheres should use entry query builder, not stache

---

src/Commands/ImportCollections.php
src/Commands/ImportGlobals.php
src/Commands/ImportNavs.php

This PR fixes an issue where you get asked to confirm what you want to import for every loop iteration with collection trees, nav and globals.

Fix looping issues in imports

---

src/Forms/Submission.php

If the id from the model is not passed back to the FileEntry, it will always create a new submission on save
Closes #439

Fix submission is newly created on save

---

src/Globals/Variables.php
tests/Globals/GlobalsetTest.php

Defer to the repository rather than saving ourselves.
Closes https://github.com/statamic/eloquent-driver/issues/441

Ensure global variables save

---

src/Assets/AssetContainer.php
tests/Assets/AssetContainerTest.php

This PR updates eloquent AssetContainers to not specify its own folders() method, instead deferring to the method in core, which queries via AssetContainerContents. The end result of this is that when using eloquent assets it will query the folder list from the database. 
Closes https://github.com/statamic/eloquent-driver/issues/443

Get AssetContainer::folders() from eloquent table

---

src/Assets/Asset.php

Closes https://github.com/statamic/eloquent-driver/issues/445

Prevent n+1 queries on asset meta exists

---

src/Assets/Asset.php
tests/Assets/AssetTest.php

Closes https://github.com/statamic/eloquent-driver/issues/448

Asset blink should cache the asset not the model

---

src/Assets/Asset.php
src/Assets/AssetContainerContents.php
tests/Assets/AssetTest.php

Closes https://github.com/statamic/eloquent-driver/issues/450

Don't blink asset-meta-exists if the file doesnt exist

---

src/Assets/Asset.php
src/Assets/AssetRepository.php
tests/Assets/AssetContainerTest.php
tests/Assets/AssetTest.php

This PR refactors assets to store $model to avoid the blink cache/meta issues.

Store model reference on assets

---

src/Entries/EntryQueryBuilder.php
tests/Data/Entries/EntryQueryBuilderTest.php

Currently ordering by a date column whose `mode` is set to `range` breaks with error
`SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type date: "{"end": "2025-06-30", "start": "2025-06-01"}" `...
This PR enables such orderings: it orders by start date and when those values are equal additionally by end date, both in the requested direction.

enable order by date range column

---

database/migrations/2024_07_16_100000_create_sites_table.php
database/migrations/updates/add_order_to_sites_table.php.stub
src/ServiceProvider.php
src/Sites/Sites.php
src/Updates/AddOrderToSitesTable.php
tests/Sites/SitesTest.php

This PR adds `order` to the sites table to ensure that sites can be re-ordered once initially created.
Closes https://github.com/statamic/eloquent-driver/issues/465

Add order to sites column

---

src/Globals/Variables.php
tests/Globals/GlobalVariablesTest.php

Variables with an origin shouldnt merge the origin data as it removes any linked 'sync' in the CP.
Closes https://github.com/statamic/eloquent-driver/issues/467

Prevent global variables merging origin data

---

src/Assets/Asset.php
tests/Assets/AssetTest.php

This PR fixes the same issue I was trying (but failed) to address in this PR to core: https://github.com/statamic/cms/pull/11983
It solves the issue of assets being only partially loaded when using the `AssetContainer()->asset()` method.  That method is used by a few critical locations chief among them being the `GlideController` in core.  This is the method call chain that causes issue:
- `Statamic\Assets\AssetContainer->asset()`
- `Statamic\Assets\AssetContainer->makeAsset()`
- `Statamic\Assets\Asset->hydrate()`
- `Statamic\Eloquent\Assets\Asset->meta()`
- `Statamic\Eloquent\Assets\Asset->model()`
Notice that chain never calls the `Statamic\Eloquent\Assets\Asset->fromModel()` method like the `Statamic\Eloquent\Assets\AssetQueryBuilder` does.  This means that when `Asset->meta()` calls …

[4.x] Always load model for assets

---

src/Commands/ImportEntries.php

Remove collection facade clearing, this is a hangover from when the import entries and collections were the same script.
Ensure we're using the bound entry class if it exists.

Tidy up entries import

---

src/Entries/EntryQueryBuilder.php
tests/Data/Entries/EntryQueryBuilderTest.php

The `QueriesJsonColumns` trait was introduced in #487. This pull request refactors the `EntryQueryBuilder` to use it to save duplicating logic between the two places.

Use `QueriesJsonColumns` trait in entry query builder

---

src/Assets/AssetContainer.php
src/Commands/ExportAssets.php

We removed various options from Asset Containers in statamic/cms#12281, in favour of permissions. This pull request drops support for these options in the Eloquent Driver.

[5.x] Drop support for old asset container options

---

database/migrations/updates/relate_form_submissions_by_handle.php.stub

After republishing the from migrations the character limit was removed resulting in a varchar(255) string column.
I kind of feel like there's no need to replicate this migration change in the packaged migrations since it's not presently there.
This fix should address anyone who's newly installed the package and who's freshly published the migrations.
closes #502 
ref #503

Updates form_submission migration stubs to match the package migrations 
