- src/Entries/EntryQueryBuilder.php
- src/Taxonomies/TermQueryBuilder.php
> Prevent eloquent eager loading relationships

- src/Entries/EntryQueryBuilder.php
- src/Taxonomies/TermQueryBuilder.php
Fix my mistake in reassigning values to variables, I've no idea what I was thinking.
Fixes #72
> Fix paginate methods in query builders

- src/Entries/Entry.php
fixes https://github.com/statamic/eloquent-driver/issues/65
> overwrite `lastModified()`

- src/Entries/EntryRepository.php
- src/Taxonomies/TermRepository.php
> Store entry to blink cache on save

- src/Entries/EntryQueryBuilder.php
Noticed this was missing while working on #57
> Apply selectedQueryColumns on transform too

- src/Forms/Submission.php
- tests/Forms/FormSubmissionTest.php
Hi , i was tinkering with form submission then i noticed that created_at being null. Can you review my changes to see if it fixes the problem. thank you
> prevent crated_at being null while submitting a from submission

- composer.json
> Support Statamic 3.4

- src/Commands/ImportTaxonomies.php
Fixes #81 by asking user to confirm which of taxonomies or terms (or both) they want to import
> Change taxonomy import to make importing taxonomies/terms optional

- src/Assets/AssetContainer.php
This PR adds the ability to save image presets in the Asset Container settings.
> Add presets to asset container settings

- src/Entries/Entry.php
Fixes: https://github.com/statamic/eloquent-driver/issues/79
> Set Entry updated_at to the timestamp of the Carbon object

- src/Assets/AssetContainerRepository.php
- src/Collections/CollectionRepository.php
- src/Fields/FieldsetRepository.php
- src/Globals/GlobalRepository.php
- src/Taxonomies/TaxonomyRepository.php
> Change blink handle for 'all' as it clashes with handles of 'all'

- src/Taxonomies/TermQueryBuilder.php
Another attempt at a performance improvement from the [conversation here](https://github.com/statamic/eloquent-driver/issues/110)
> Blink entry queries in term query builder

- src/Commands/ImportAssets.php
- src/Commands/ImportBlueprints.php
- src/Commands/ImportCollections.php
- src/Commands/ImportEntries.php
- src/Commands/ImportForms.php
- src/Commands/ImportGlobals.php
- src/Commands/ImportNavs.php
- src/Commands/ImportTaxonomies.php
> Clear resolved facades before changing them on imports

- src/Taxonomies/TermRepository.php
Super tiny change to fix the hyphenated taxonomies in term uris.
> Fix to hyphenated taxonomies from uri

- src/Entries/EntryQueryBuilder.php
`whereIn` has 'values' not 'value', so we need to handle that properly when looking for collections in the where clauses.
> Handle whereIn() in new ordering clause logic

- src/Commands/ExportAssets.php
- src/Commands/ExportCollections.php
- src/Commands/ExportNavs.php
- src/Commands/ExportTaxonomies.php
- src/Commands/ImportAssets.php
- src/Commands/ImportCollections.php
- src/Commands/ImportNavs.php
- src/Commands/ImportTaxonomies.php
When running the import or exports in for example CI/CD or Taskfile; it was not possible to skip the questions. I've added the --force parameter to skip the questions and continue with the action.
> Add --force to imports & exports

- src/Revisions/Revision.php
Closes https://github.com/statamic/eloquent-driver/issues/229
> Store revision attribute id due to change in core

- src/Assets/Asset.php
- src/Commands/ImportAssets.php
This PR fixes eloquent assets import by changing the approach to be similar to the more recent imports.
Closes https://github.com/statamic/eloquent-driver/issues/225
> Fix asset import bug

- database/migrations/updates/add_id_to_attributes_in_revisions_table.php.stub
- src/ServiceProvider.php
- src/Updates/AddIdToAttributesInRevisionsTable.php
Fixes https://github.com/statamic/eloquent-driver/issues/229 for existing revisions
> Update old broken revisions after updating to Statamic v4.41.0

- src/Fields/BlueprintRepository.php
Closes https://github.com/statamic/eloquent-driver/issues/237
> Fix Blueprint::find with ::

- src/Taxonomies/TaxonomyRepository.php
Closes https://github.com/statamic/eloquent-driver/issues/242
> Ensure we get a valid taxonomy model, or null otherwise

- database/migrations/2024_03_07_100000_create_asset_table.php
Closes https://github.com/statamic/eloquent-driver/issues/256
> Add unique() constraint to asset index

- src/Assets/Asset.php
This PR fixes https://github.com/statamic/eloquent-driver/issues/258#issuecomment-1997579873 and https://github.com/statamic/eloquent-driver/issues/251 in a different manner, by going to the root cause of the extra meta rows.
This was being caused by overly aggressive caching (cache vs blink) and the generateMeta method writing meta, which again was a cache optimisation that we have had to roll back.
@jstoks @modrictin @shawinigan I've run this with all the filenames you provided and it works ok for me - can you pull the changes down and verify they work in your environments?
> Don't write meta when we should only be generating it

- src/Assets/AssetRepository.php
- src/Commands/ImportBlueprints.php
Statamic 5.x is going to drop support for helper functions, so this driver needs to as well.
See https://github.com/statamic/cms/pull/9811
> Remove helper functions

- README.md
This pull request refreshes the Eloquent Driver's documentation, to go alongside the changes introduced in statamic/cms#9669.
This PR should be merged whenever Statamic 5 compatibility is released for this addon.
> Statamic 5: Docs Refresh

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This pull request adds GitHub Issue Templates, to help streamline support a little bit.
> GitHub Issue Templates

- src/Entries/EntryQueryBuilder.php
This PR changed to date cast to a datetime cast when time is enabled on date fields.
> Date(time) sorting does not take time into account

- src/Commands/SyncAssets.php
Closes https://github.com/statamic/eloquent-driver/issues/298
> Only create asset during sync if it doesnt exist

- database/migrations/2024_05_15_100000_modify_form_submissions_id.php
https://github.com/statamic/eloquent-driver/pull/305 incorrectly used double, it should have been decimal.
> Change form submissions migration to use decimal

- README.md
After reading #338, I thought the documentation for this feature could be improved slightly.
> Improve data column mapping docs

- src/Assets/AssetContainer.php
- Continuation of #381
- Read sort direction and field from config
- Restore into json
> Apply and restore sort direction on asset containers

- src/Taxonomies/Term.php
- tests/Terms/TermTest.php
Closes https://github.com/statamic/eloquent-driver/issues/408
> Store updated_at in terms as timestamp

- src/Entries/Entry.php
- src/Forms/Form.php
- src/Forms/Submission.php
- src/Globals/Variables.php
- src/Taxonomies/Term.php
- tests/Entries/EntryTest.php
- tests/Forms/FormSubmissionTest.php
- tests/Forms/FormTest.php
- tests/Terms/TermTest.php
Complements: https://github.com/statamic/cms/pull/11591
> Prevent null values from being saved to data

- database/migrations/2024_05_15_100000_modify_form_submissions_id.php
> Fix rolling back `modify_form_submissions` migration

- src/Forms/Submission.php
- tests/Forms/FormSubmissionTest.php
This PR ensures that the delete method returns true, and that saveQuietly and deleteQuietly work using this driver too.
Closes #418
> Bring FormSubmission save/delete inline with core

- src/Entries/Entry.php
Get template from data() not template variable
Closes #414
> Fix template not being set correctly

- composer.json
- src/Assets/AssetContainerContents.php
See: https://github.com/statamic/cms/pull/11481
> Use asset container contents cache store

- src/Forms/SubmissionQueryBuilder.php
- tests/Forms/FormSubmissionTest.php
Closes https://github.com/statamic/cms/issues/11971
> FormSubmission transform should return a DataCollection

- src/Entries/EntryQueryBuilder.php
Fixes a regression caused by https://github.com/statamic/cms/pull/12027
Closes #490
> [4.x] Pluck collectionHandle not collection

- tests/Globals/GlobalVariablesTest.php
This pull request fixes `GlobalVariablesTest`, which was failing on `master` due to changes in #411.
> [6.x] Fix GlobalVariablesTest
